services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: bind
        source: node_modules
        target: /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PORT: ${PORT}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - database:/data/db
    logging:
      driver: none
    restart: unless-stopped

volumes:
  database:
  node_modules:
