services:
  payload:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      PORT: ${PORT}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      NODE_OPTIONS: ${NODE_OPTIONS}
    restart: unless-stopped

  mongo:
    image: mongo:latest
    init: true
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - database:/data/db
    logging:
      driver: none
    restart: unless-stopped

volumes:
  database:
